const GET_ALL_USER_INFO_REQUEST = 'user/GET_ALL_USER_INFO_REQUEST';
const GET_ALL_USER_INFO_REQUEST_SUCCESS =
  'user/GET_ALL_USER_INFO_REQUEST_SUCCESS';
const GET_ALL_USER_INFO_REQUEST_FAILSE =
  'user/GET_ALL_USER_INFO_REQUEST_FAILSE';

export {
  GET_ALL_USER_INFO_REQUEST,
  GET_ALL_USER_INFO_REQUEST_SUCCESS,
  GET_ALL_USER_INFO_REQUEST_FAILSE,
};
